[build]
  functions = "netlifyFunctions"
  publish = "public"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"

[dev]
  port = 8888
  targetPort = 3000